### PR TITLE
Allow MaxNestedLevels to be up to 65535

### PR DESCRIPTION
**Pull request by immesys**
### Description

This is a preemptive pr that solves #354. Namely, it increases MaxNestedLevels and adds a test for a deeply nested object. It's not a particularly hard thing to solve, but I wanted to be helpful. Let me know if you would like to pick a different maximum for MaxNestedLevels, or make any other changes.

#### PR Was Proposed and Welcomed in Currently Open Issue

- [] This PR was proposed and welcomed by maintainer(s) in issue #354
- [x] Closes or Updates Issue #354 

#### Checklist (for code PR only, ignore for docs PR)

- [x] Include unit tests that cover the new code
- [x] Pass all unit tests 
- [ ] Pass all 18 ci linters (golint, gosec, staticcheck, etc.)
- [x] Sign each commit with your real name and email.  
      Last line of each commit message should be in this format:  
      Signed-off-by: Firstname Lastname <firstname.lastname@example.com>
- [x] Certify the Developer's Certificate of Origin 1.1
      (see next section).

#### Certify the Developer's Certificate of Origin 1.1

- [x] By marking this item as completed, I certify 
      the Developer Certificate of Origin 1.1.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Review by fxamacker — CHANGES_REQUESTED** [review]
Looks good and thank you for doing this!  :+1:  

Just a few nitpicks to make doc match the code and make beginning of error messages consistent with others.

**Comment by fxamacker** [comment]
Added issue #354 to milestone 2.5.0.

**Comment by immesys** [comment]
Thanks for reviewing, sorry about the off-by-one errors. I made the requested changes as an amendment to the previous commit to also fix the fact that the email in the signature may have been wrong

**Review by fxamacker — APPROVED** [review]
LGTM!  :+1: Thanks again for opening issue and this PR!

**Pull request merged**
