### PR TITLE
Add encoding option to specify how omitempty fields are encoded

### PR DESCRIPTION
**Pull request by dinhxuanvu**
### Description

The current behavior in the library is to omits if field value would encode as empty JSON value. This behavior is different from the bahavior in golang encoding/json which omits if field value is an empty Go value (defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string). The OmitEmptyMode = 1 is added to encoding option so that cbor would decode omitempty fields similarly to encoding/json in go.

#### PR Was Proposed and Welcomed in Currently Open Issue

- [ ] This PR was proposed and welcomed by maintainer(s) in issue #445 
- [ ] Closes or Updates Issue #445 

#### Checklist (for code PR only, ignore for docs PR)

- [x] Include unit tests that cover the new code
- [x] Pass all unit tests 
- [x] Pass all 18 ci linters (golint, gosec, staticcheck, etc.)
- [x] Sign each commit with your real name and email.  
      Last line of each commit message should be in this format:  
      Signed-off-by: Firstname Lastname <firstname.lastname@example.com>
- [x] Certify the Developer's Certificate of Origin 1.1
      (see next section).

#### Certify the Developer's Certificate of Origin 1.1

- [x] By marking this item as completed, I certify 
      the Developer Certificate of Origin 1.1.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Review by fxamacker — CHANGES_REQUESTED** [review]
@dinhxuanvu  Thanks for opening this PR!  :+1: 

I left some feedback for your consideration and will try to include this PR in v2.6.0 if possible.

Thanks again!

**Comment by dinhxuanvu** [comment]
@fxamacker Thanks so much for the feedbacks. All are addressed! PTAL

**Comment by dinhxuanvu** [comment]
Force-pushed to fix a small fix with lint (variable name).

**Comment by fxamacker** [comment]
@dinhxuanvu Thanks for opening issue and contributing this PR!  :+1: 

I'd like to include this in v2.6 and will take a closer look this weekend!

**Review by fxamacker — APPROVED** [review]
@dinhxuanvu  Thanks for updating the PR!  LGTM!  :+1:

**Pull request merged**
