### PR TITLE
Use io.WriterTo interface when provided by the type

### PR DESCRIPTION
**Pull request by omerfirmak**
### Description

`MarshalBinary` and `MarshalCBOR` interfaces result in heap memory allocations. `io.WriterTo` & `io.ReadFrom` eliminates the need for temporary heap buffers.  

#### Checklist (for code PR only, ignore for docs PR)

- [X] Include unit tests that cover the new code
- [X] Pass all unit tests 
- [X] Pass all 18 ci linters (golint, gosec, staticcheck, etc.)
- [X] Sign each commit with your real name and email.  
      Last line of each commit message should be in this format:  
      Signed-off-by: Firstname Lastname <firstname.lastname@example.com>
- [X] Certify the Developer's Certificate of Origin 1.1
      (see next section).

#### Certify the Developer's Certificate of Origin 1.1

- [X] By marking this item as completed, I certify 
      the Developer Certificate of Origin 1.1.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by omerfirmak** [comment]
Pinging @fxamacker. we would highly benefit from this.

**Comment by fxamacker** [comment]
@omerfirmak Thanks for contributing this PR!  I can take a look this weekend.

**Comment by fxamacker** [comment]
I understand the value of reducing GC and the approach taken by this PR.  However, there are some issues:

- `isEmptyWriterTo(v reflect.Value) (bool, error)` might not work.  After data is read for its length using `lenData, err := m.WriteTo(io.Discard)`, data isn't available for encoding.

- Merging this PR can lead to other requests to add support for additional readers and writers,  increasing bloat.  There may be other ways to reduce GC without this drawback.

Currently, the master branch and [recent tags](https://github.com/fxamacker/cbor/releases) since 2.5.0-beta have  memory improvements for `Encoder`.  Also, maybe you can reuse the same buffer as `io.Writer` for `Encoder`, to further reduce allocs.

For these reasons, maybe we can try other approaches to reduce GC rather than continuing work on this PR.

**Comment by fxamacker** [comment]
Closing this for now but please feel free to comment or reopen.

**Pull request closed without merging**
